# Generated by Django 6.0 on 2025-12-08 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scanning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(default='PDF', max_length=50, verbose_name='نوع التقرير')),
                ('file_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='مسار الملف')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='الحالة')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='scanning.scan', verbose_name='عملية المسح')),
            ],
        ),
    ]
