# Generated by Django 6.0 on 2025-12-12 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
        ('scanning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='file_path',
        ),
        migrations.AddField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(default='PDF', max_length=50, verbose_name='Report Type'),
        ),
        migrations.AlterField(
            model_name='report',
            name='scan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='scanning.scan', verbose_name='Scan Operation'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
